# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false
# Mod properties
version=2.6.6.1
maven_group=rip.ysm
archives_name=openysm
mod_id=yes_steve_model
mod_name=Yes Steve Model
