[versions]
# Minecraft & Fabric Properties
minecraft = "1.21.11"
parchment-mappings = "2025.12.20"
fabric-loader = "0.19.5"
fabric-api = "0.141.6+1.21.11"
fabric-language-kotlin = "1.14.1+kotlin.2.4.20"
cardinal-components = "7.3.2"
forge-config-api-port = "21.11.1"
night-config = "3.9.0"
iris = "1.10.8+1.21.11-fabric"
touhou-little-maid = "0.8.5-neo1.5.3+mc1.21.11"
crawl = "Ias4IRqo"
modmenu = "17.0.1"
concentus = "1.0.0"
vorbis-java = "0.8"
carryon = "2.9.2"
aircompressor = "2.0.3"
sodium = "mc1.21.11-0.8.15-beta.1-fabric"
antlr4 = "4.13.2"
glsl-transformer = "2.0.2"
jcpp = "1.4.14"

# Build & Toolchain
loom = "1.17-SNAPSHOT"
kotlin = "2.4.20"
jvm-toolchain = "25"
jvm-target = "21"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
forge-config-api-port = { module = "fuzs.forgeconfigapiport:forgeconfigapiport-fabric", version.ref = "forge-config-api-port" }
night-config-core = { module = "com.electronwill.night-config:core", version.ref = "night-config" }
night-config-toml = { module = "com.electronwill.night-config:toml", version.ref = "night-config" }
cardinal-components-base = { module = "org.ladysnake.cardinal-components-api:cardinal-components-base", version.ref = "cardinal-components" }
cardinal-components-entity = { module = "org.ladysnake.cardinal-components-api:cardinal-components-entity", version.ref = "cardinal-components" }
imagestream = { module = "com.github.TartaricAlkaline:ImageStream", version = "-SNAPSHOT" }
iris = { module = "maven.modrinth:iris", version.ref = "iris" }
touhoulittlemaid-fabric = { module = "libs:touhoulittlemaid-fabric", version.ref = "touhou-little-maid" }
crawl = { module = "maven.modrinth:crawl", version.ref = "crawl" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
concentus = { module = "com.plasmoverse:concentus", version.ref = "concentus" }
vorbis-java-core = { module = "org.gagravarr:vorbis-java-core", version.ref = "vorbis-java" }
carryon = { module = "tschipp.carryon:carryon-fabric-1.21.11", version.ref = "carryon" }
aircompressor = { module = "io.airlift:aircompressor", version.ref = "aircompressor" }
sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }
antlr4-runtime = { module = "org.antlr:antlr4-runtime", version.ref = "antlr4" }
glsl-transformer = { module = "io.github.douira:glsl-transformer", version.ref = "glsl-transformer" }
jcpp = { module = "org.anarres:jcpp", version.ref = "jcpp" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "loom" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
